# Generated by Django 5.1.1 on 2024-10-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(default='product description')),
                ('product_price', models.PositiveIntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
