# Generated by Django 5.1.1 on 2024-10-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_products_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
